// Generated by CoffeeScript 1.10.0
(function() {
  var CarouselNavigator, ProjectDisplayer, SkillDisplayer;

  CarouselNavigator = {
    bindNavLinks: function() {
      return $('header nav .carousel-nav-trigger').click(function(ev) {
        var slideIndex;
        ev.preventDefault();
        slideIndex = parseInt(this.dataset.targetSlideIndex);
        CarouselNavigator.moveTo(slideIndex);
        if (slideIndex === 2) {
          $('.skill-circle').circleProgress('redraw');
        }
        $('nav a.selected').removeClass('selected');
        return $(this).addClass('selected');
      });
    },
    carouselElement: function() {
      return $('#nsg-carousel');
    },
    init: function() {
      CarouselNavigator.carouselElement().carousel('pause');
      return CarouselNavigator.bindNavLinks();
    },
    moveTo: function(i) {
      CarouselNavigator.carouselElement().carousel(i);
      return CarouselNavigator.carouselElement().carousel('pause');
    }
  };

  SkillDisplayer = {
    init: function() {
      $.circleProgress.defaults.size = 1000;
      $.circleProgress.defaults.startAngle = -Math.PI / 2;
      return $('.skill-circle').circleProgress();
    }
  };

  ProjectDisplayer = {
    init: function() {
      return $('#portfolio .project').click(function(ev) {
        ev.preventDefault();
        $('#project-details-modal').modal('show');
        $('#projects-carousel').carousel(parseInt(this.dataset.targetSlide));
        return $('#projects-carousel').carousel('pause');
      });
    }
  };

  (new WOW).init();

  $(function() {
    CarouselNavigator.init();
    SkillDisplayer.init();
    return ProjectDisplayer.init();
  });

}).call(this);
